### ISSUE TITLE
Inline svg on Firefox not working

### ISSUE THREAD

**Issue by Dgiulian** [beyerleinf/ngx-dnd#86]
**Describe the bug**
When trying to drag an element that contains an inline SVG it doesn't work in firefox. However, in Chrome is working correctly. 
I've tried replacing the SVG with an img element, and it works.  

**Firefox version: 68.0.1**

**Example Code**
```
<tr *ngFor="let butaca of tipo_butacas">
   <td dnd-draggable  [dragEnabled]="true" [dragData]="butaca.tipo_butaca" >
        <svg
         xmlns="http://www.w3.org/2000/svg"
         width="24.999"
         height="19.345"
         viewBox="0 0 24.999 19.345"
         [ngStyle]="{ fill: fill }" >
         <g id="butaca" transform="translate(-2 -2)">
          <path
             d="M26.384,35.346a2,2,0,0,1-2-2V31.438a.987.987,0,0,1-1.384-.9V20.811a.987.987,0,0,1,1.384-.9V18a2,2,0,0,1,2-2H44.616a2,2,0,0,1,2,2v1.908a.987.987,0,0,1,1.384.9v9.724a.987.987,0,0,1-1.384.9v1.908a2,2,0,0,1-2,2Z"  transform="translate(-21 -14)" />
         </g>
       </svg>
</td>
<td dnd-draggable  [dragEnabled]="true" [dragData]="butaca.tipo_butaca" >
   <img src='../../../assets/butaca-discapacitado.svg' />
</td>
</tr>
```

In this example, the first td does not allow the user to drag it. However, the second td containing an img element does.

**Comment by beyerleinf** [comment]
Hi! Thanks for creating an issue.

It appears to me that `dnd-draggable` doesn't work at all under Firefox. Although I know it has in the past.
If you replace the SVG with text it still won't drag under Firefox. I will be having a look at it but if the fix is somewhat more complex I'm afraid I won't fix that.

I'm in the middle of creating a demo repo where I compare this package to Angular native drag and drop. I will get back to you later and maybe refer you to that repo.

Have a nice evening.

**Comment by beyerleinf** [comment]
Quick follow up: It seems that none of the features of this package work in firefox. I'm going to dig a bit but I can't promise anything right now.

**Comment by beyerleinf** [comment]
Okay, so somehow one line got lost somewhere which prevents this package from working in Firefox entirely. Expect a new Version later
